### ISSUE TITLE
still maintained?

### ISSUE THREAD

**Issue by oasys** [soerenbe/soerenbe-syslog_ng#8]
I've been using this module (for a relatively complex syslog-ng installation) for many years.  Thanks!

I've recently embarked on upgrading this old puppet 3 installation on Debian Jessie to puppet 6 on Debian Buster.   Syslog-ng is now complaining about my configuration:

>WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 3.19 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file.;

I haven't delved any further into this, but thought I'd ask what your plans for this module are?   The last change was 4 years ago.   There are more recent modules on the puppet forge, but they have a different interface, so I would have to update my code.   Where do you recommend I put my efforts:  submitting PRs to modernize this module (at least to support syslog-ng's newer config format), or assume it is unmaintained and migrate to another module?

Thanks again for the many years we have used this nicely-flexible module!

**Comment by soerenbe** [comment]
Hi!
Thanks for your positiv feedback!

Since I no longer use Puppet, I don't have any plans to update this module. If you want you can take over this. Otherwise I would make plans to fork it or migrate to another module. :-)

**Comment by oasys** [comment]
Thanks for the quick reply.  It turns out it was simpler than I thought.  I just generalized the support you had added for stretch to also work with my version.   For now, it is in a private fork.  If I decide to modernize the module and maintain it, I'll reach out to take you up on your offer.

For the benefit of others that find this:

```diff
diff --git a/files/scl.conf.stretch b/files/scl.conf.debian
similarity index 100%
rename from files/scl.conf.stretch
rename to files/scl.conf.debian
diff --git a/manifests/install.pp b/manifests/install.pp
index ac13659..7cc956c 100644
--- a/manifests/install.pp
+++ b/manifests/install.pp
@@ -13,9 +13,9 @@ class syslog_ng::install {
     purge   => true,
     force   => true,
   }
-  if $::lsbdistcodename == 'stretch' {
+  if $::lsbdistid == 'Debian' {
     file { '/etc/syslog-ng/scl.conf':
-      source => 'puppet:///modules/syslog_ng/scl.conf.stretch',
+      source => 'puppet:///modules/syslog_ng/scl.conf.debian',
     }
   }
   else {
diff --git a/manifests/params.pp b/manifests/params.pp
index 0598a79..2756dbe 100644
--- a/manifests/params.pp
+++ b/manifests/params.pp
@@ -3,6 +3,9 @@ class syslog_ng::params {
   if $::lsbdistcodename == 'stretch' {
     $version        = '3.8'
   }
+  elsif $::lsbdistcodename == 'buster' {
+    $version        = '3.19'
+  }
   else {
     $version        = '3.5'
   }
```
